import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import useTranslation from '../locales'

const Home: NextPage = () => {
  const t = useTranslation()

  return (
    <>
      <Head>
        <title>
          {t('common:site-domain')} | {t('common:home')}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/favicon.ico" />
      </Head>

      <Navbar />

      <section className="section">
        <div className="container">
          <div className="columns is-vcentered is-multiline">
            <div className="column is-6-tablet is-3-desktop has-text-right-desktop has-text-white">
              <p className="is-size-1">{t('common:site-domain')}</p>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </>
  )
}

export default Home
